### ISSUE TITLE
how about add code coverage and tests?

### ISSUE THREAD

**Issue by calidion** [tniessen/node-mceliece-nist#1]
or can the library be translated to pure js?

**Comment by tniessen** [comment]
> how about add code coverage and tests?

@calidion Unit tests are currently in [/test.js](https://github.com/tniessen/node-mceliece-nist/blob/11ee2355ebc2f4e94b470a3b7fc85fc99ec6e8a3/test.js), and they use test vectors from [/test_vectors.json](https://github.com/tniessen/node-mceliece-nist/blob/11ee2355ebc2f4e94b470a3b7fc85fc99ec6e8a3/test_vectors.json).

Coverage could be added at some point, but other issues are more important, e.g., native Windows support without WebAssembly.

> or can the library be translated to pure js?

In theory, it could be using Emscripten, however, it already supports WebAssembly, which runs in all major browsers and Javascript runtimes. I don't see a need for a pure JS port.

**Comment by tniessen** [comment]
I have upgraded to the round-4 submission package and adapted the tests accordingly.

A pure JS version is out of scope at this point given the widespread support for WebAssembly. For non-Node.js environments, my other PQC package https://github.com/tniessen/node-pqclean can be used, which also supports Windows natively.
